insert into tt_user values
(
--user_id
1,


--user_created_datetime
now,
--user_created_user_id
1,
--user_last_updated_datetimedatetime
now,
--user_last_updated_user_id 
1,


--user_group_id 
1,
--user_login
'TTSYSTEM',
--user_display_name 
'Administrator',
--user_password 
'77D8ED17B04C7D2881A26647BDF703EB',


--user_city 
'',
--user_postal_code
'',
--user_state_id 
0,
--user_country_id 
0,

--user_status 
1,
--user_password_never_expires
0,
--user_must_change_password_next_login
0,
--user_most_recent_password_change_datetime 
now,

--user_most_recent_login_datetime 
now,
--user_failed_login_attempts_count
0,
--user_def1 
'',
--user_def2 
'',

--user_def3 
'',
--user_enforce_ip_login_limit
0,
--user_ip_login_limit 
1,
--user_email
'',

--user_restrict_customer_default_editing
0,
--user_address
'',
--user_phone
'',
--user_def4
'',

--user_def5 varchar(50)
'',
--user_def6 varchar(50)
'',
--user_x_trader_mode
0,
--user_login_attempt_key
0,

--user_fix_adapter_enable_order_logging
0,
--user_fix_adapter_enable_price_logging
0,
--user_fix_adapter_default_editing_allowed
0,
--user_xrisk_sods_allowed
0,

--user_xrisk_manual_fills_allowed
0,
--user_xrisk_prices_allowed
0,
--user_xrisk_instant_messages_allowed
0,
--user_cross_orders_allowed
1,

--user_user_setup_user_type 
1,
--user_smtp_host
'',
--user_smtp_port
25,
--user_smtp_requires_authentication
0,

--user_smtp_login_user
'',
--user_smtp_login_password
'',
--user_smtp_use_ssl
0,
--user_smtp_from_address
'',

--user_smtp_subject
'',
--user_smtp_body
'',
--user_smtp_include_username_in_message
0,
--user_smtp_enable_settings
0,

--user_quoting_allowed
1,
--user_wholesale_trades_allowed
1,
--user_fmds_allowed
1,
--user_credit,
0,

--user_currency,
'USD',
--user_allow_trading,
1,
--user_force_logoff_switch
0,
--user_fix_adapter_role
0,


--user_cross_orders_cancel_resting
1,
--user_fmds_primary_ip
'',
--user_fmds_primary_port
10200,

--user_fmds_primary_service
250,
--user_fmds_primary_timeout_in_secs
30,
--user_fmds_secondary_ip
'',
--user_fmds_secondary_port
0,

--user_fmds_secondary_service
0,
--user_fmds_secondary_timeout_in_secs
0,
--user_gui_view_type
0,
--user_use_user_level_fmds_settings
0,
--user_most_recent_failed_login_attempt_datetime
#1970-01-02 00:00:00#,
--user_marked_for_deletion_datetime
#1970-01-02 00:00:00#,
--user_ttapi_allowed
0,
--user_mgt_generation_method
0,
--user_staged_order_creation_allowed,
0,
--user_staged_order_claiming_allowed,
0,
--user_dma_order_creation_allowed,
1,
--user_fix_staged_order_creation_allowed,
0,
--user_fix_dma_order_creation_allowed
1,
--user_use_pl_risk_algo
0,
--user_xrisk_update_trading_allowed_allowed
0,
--user_ttapi_admin_edition_allowed
0,
--user_most_recent_login_datetime_for_inactivity
#1970-01-02 00:00:00#,
--user_use_simulation_credit,
0,
--user_simulation_credit,
0,
--user_on_behalf_of_allowed
0,
--user_mgt_generation_method_member
'',
--user_mgt_generation_method_group
'',
--user_non_simulation_allowed
1,
--user_organization
'',
--user_simulation_allowed
1,
--user_machine_gun_orders_allowed
1,
--user_persist_orders_on_eurex
0,
--user_prevent_orders_based_on_price_ticks
0,
--int_user_prevent_orders_price_ticks
0,
--user_enforce_price_limit_on_buysell_only
1,
--user_prevent_orders_based_on_rate
0,
--int_user_prevent_orders_rate
0,
--user_gtc_orders_allowed
1,
--user_undefined_accounts_allowed
0,
--user_account_changes_allowed
0,
--user_no_sod_user_group_restrictions
1,
--user_liquidate_exceeding_position_limits_allowed
1,
--user_billing1 varchar(50)
'',
--user_billing2 varchar(50)
'',
--user_billing3 varchar(50)
'',
--user_never_locked_by_inactivity
0,
--user_most_recent_login_ip
'',
--user_most_recent_xt_version
'',
--user_most_recent_fa_version
'',
--user_most_recent_xr_version
'',
--user_algo_deployment_allowed
0,
--user_algo_sharing_allowed
0,
--user_individually_select_admin_logins
0,
--user_ignore_pl
0,
--user_ignore_margin
0,
--user_claim_own_staged_orders_allowed
1,
--user_wholesale_orders_with_undefined_accounts_allowed
1,
--user_account_permissions_enabled
0,
--user_can_submit_market_orders
1,
--user_xrisk_allowed
1,
--user_2fa_required
0,
--user_xtapi_allowed
1,
--user_autotrader_allowed
1,
--user_autospreader_allowed
1,
--user_can_submit_iceberg_orders
1,
--user_can_submit_time_sliced_orders
1,
--user_can_submit_volume_sliced_orders
1,
--user_can_submit_time_duration_orders
1,
--user_can_submit_volume_duration_orders
1,
--user_sms_number
'',
--user_gf_cbot
0,
--user_gf_cme
0,
--user_gf_cme_europe
0,
--user_gf_comex
0,
--user_gf_nymex
0,
--user_gf_dme
0,
--user_netting_cbot
0,
--user_netting_cme
0,
--user_netting_cme_europe
0,
--user_netting_comex
0,
--user_netting_nymex
0,
--user_netting_dme
0,
--user_netting_organization_id
0,
--user_fa_category_id
0,
--user_2fa_required_mode
0,
--user_fix_subscribers_cbot
0,
--user_fix_subscribers_cme
0,
--user_fix_subscribers_cme_europe
0,
--user_fix_subscribers_comex
0,
--user_fix_subscribers_nymex
0,
--user_fix_subscribers_dme
0,
--user_mgt_auto_login
1,
--user_gf_ice_fut_can
0,
--user_gf_ice_phy_env
0,
--user_gf_ice_ifus_gas
0,
--user_gf_ice_ifeu_oil
0,
--user_gf_ice_ifus_pwr
0,
--user_gf_ice_ifeu_com
0,
--user_gf_ice_fut_us
0,
--user_gf_ice_ifeu_fin
0,
--user_gf_ice_endex
0,
--user_gf_ice_fut_sg
0,
--user_aggregator_allowed
1,
--user_sniper_orders_allowed
1,
--user_eu_config_1_allowed
0,
--user_eu_config_1
'',
--user_eu_config_2_allowed
0,
--user_eu_config_2
''
)
go
